version: '3.1'
services:
  automation:
    container_name: starman-auto
    working_dir: /app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9323:9323
    ipc: host
    command: [ 'npx', 'playwright', 'test' ]
